In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr,type(arr))
print(np.__version__)

[1 2 3 4] <class 'numpy.ndarray'>
1.24.3


In [9]:
#one dimension array
import numpy as np
arr=np.array(2)
print(arr,type(arr),arr.ndim)
arr1=np.array([1,2,3,4])
print(arr1,type(arr1),arr1.ndim)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2,type(arr2),arr2.ndim)
arr3=np.array([[[1,2],[4,5]],[[100,200],[600,700]]])
print(arr3,type(arr3),arr3.ndim)
arrn=np.array(5,ndmin=5)
print(arrn,type(arrn),arrn.ndim)

2 <class 'numpy.ndarray'> 0
[1 2 3 4] <class 'numpy.ndarray'> 1
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> 2
[[[  1   2]
  [  4   5]]

 [[100 200]
  [600 700]]] <class 'numpy.ndarray'> 3
[[[[[5]]]]] <class 'numpy.ndarray'> 5


In [14]:
#accessing
print(arr1[0])
print(arr2[0,2])
print(arr3[1,0,1])

1
3
200


In [16]:
#slicing
print(arr1[0::2])
print(arr)

[1 3]
2


In [20]:
import numpy as np
arr=np.array([0,1,2,3])
newarr=arr.astype(bool)
print(arr,newarr)
print(arr.dtype)
print(newarr.dtype)

[0 1 2 3] [False  True  True  True]
int32
bool


In [22]:
arr=np.array([1,2,3,4])
new=arr.copy()
arr[1]=50
print(arr,new)

[ 1 50  3  4] [1 2 3 4]


In [4]:
arr10=np.array([199,200,345])
newa=arr10.view()
arr10[0]=143
print(arr10,newa)

[143 200 345] [143 200 345]


In [7]:
print(newa.shape)

(3,)


In [8]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
